USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE FOOTBALL_ANALYSIS
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE UEFA;

CREATE OR REPLACE SCHEMA CHAMPIONS_LEAGUE;

USE WAREHOUSE FOOTBALL_ANALYSIS;
USE DATABASE UEFA;
USE SCHEMA CHAMPIONS_LEAGUE;

CREATE OR REPLACE FILE FORMAT csv_data_format
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE STAGING_AREA;

CREATE OR REPLACE ROLE analytics1;

GRANT USAGE ON WAREHOUSE FOOTBALL_ANALYSIS TO ROLE analytics1;

GRANT ROLE analytics1 TO USER your_username;

GRANT ALL PRIVILEGES ON DATABASE UEFA TO ROLE analytics1;

GRANT ALL PRIVILEGES ON SCHEMA UEFA.CHAMPIONS_LEAGUE TO ROLE analytics1;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA UEFA.CHAMPIONS_LEAGUE TO ROLE analytics1;

SHOW GRANTS ON TABLE UEFA.CHAMPIONS_LEAGUE.DATA_2020;






